service: default
runtime: python37
instance_class: B8

basic_scaling:
    max_instances: 2
    idle_timeout: 10m

resources:
    cpu: 4
    memory_gb: 16
    disk_size_gb: 10

entrypoint: gunicorn -b 0.0.0.0:8080 main:server
